### ISSUE TITLE
既然都上spring了，那么提供http接口不过分吧

### ISSUE THREAD

**Issue by iammmmmmm** [reine-ishyanami/nhentai-java#7]
1. 如题，提供http接口供无法本地运行本程序的程序或qbot等下载nhentai。
2. 提供和 setu 一样的随机功能随机返回nhentai的接口。
3. 提供和 setu 一样的根据关键词（标签）返回随机nhentai的接口。

**Comment by reine-ishyanami** [comment]
1. 可以考虑，但需先设计请求参数和响应内容格式
2. 不考虑，可能得到令人不适的 hentai
3. 可以考虑

**Comment by iammmmmmm** [comment]
此issue已经全部实现并通过本地测试，是否可以提交pr

**Comment by reine-ishyanami** [comment]
提咯
